services:
  node:
    image: node:22-alpine
    user: ${UID:-1000}:${GID:-1000}
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /app

volumes:
  node_modules:
