name: Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx eslint "**/*.{vue,js,jsx,cjs,mjs}" --fix

      - name: Run formatter
        run: npm run format

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Apply linter and formatter changes' || echo "No changes to commit"
          git push

  test:
    runs-on: ubuntu-latest
    needs: lint-and-format

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unitary tests
        run: npm run test
        env:
          VITE_APP_NAME: Vite App

      - name: Run end-to-end tests
        run: npm run test:e2e:dev
        env:
          ELECTRON_DISABLE_GPU: 1
          CYPRESS_INSTALL_BINARY: 0

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  retrieve-dist:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download production-ready build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: retrieve-dist

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Download production-ready build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: ./dist